name: firebase_connect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_ui_auth: ^1.16.0
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.3
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  timer_count_down: ^2.2.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  table_calendar: ^3.1.2
  sqflite: ^2.4.0
  path: ^1.9.0
  flutter_spinkit: ^5.2.1
  cloudinary: ^1.2.0
  cloudinary_flutter: ^1.3.0

  # for PDF Making
  cupertino_icons: ^1.0.2

  # create pdf document
  pdf: ^3.1.0

  # save file
  path_provider: ^2.0.1

  # open pdf document
  open_file: ^3.1.0

  # format dates for invoice

  # for printing the data
  printing: ^5.13.4
  flutter_animate: ^4.5.2
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  syncfusion_flutter_pdf: ^28.1.41
  toasty_box: ^1.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/images/products/
