// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDvEZCOenjdEPIN6xKOsCQTqAZRtv-pQA',
    appId: '1:860542776358:web:59c03fcccbab15742b22e7',
    messagingSenderId: '860542776358',
    projectId: 'skwebtrial',
    authDomain: 'skwebtrial.firebaseapp.com',
    databaseURL: 'https://skwebtrial-default-rtdb.firebaseio.com',
    storageBucket: 'skwebtrial.appspot.com',
    measurementId: 'G-HC7ZP33169',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3r9opO4sv11ENl64NrWA5TdZ7vZZzYEE',
    appId: '1:860542776358:android:32bb07ca168b766b2b22e7',
    messagingSenderId: '860542776358',
    projectId: 'skwebtrial',
    databaseURL: 'https://skwebtrial-default-rtdb.firebaseio.com',
    storageBucket: 'skwebtrial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA82ukhQbXzufXKKX69R2gLl_gjmcJYhsY',
    appId: '1:860542776358:ios:1b1875c648a7f6ae2b22e7',
    messagingSenderId: '860542776358',
    projectId: 'skwebtrial',
    databaseURL: 'https://skwebtrial-default-rtdb.firebaseio.com',
    storageBucket: 'skwebtrial.appspot.com',
    iosBundleId: 'com.example.firebaseConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA82ukhQbXzufXKKX69R2gLl_gjmcJYhsY',
    appId: '1:860542776358:ios:1b1875c648a7f6ae2b22e7',
    messagingSenderId: '860542776358',
    projectId: 'skwebtrial',
    databaseURL: 'https://skwebtrial-default-rtdb.firebaseio.com',
    storageBucket: 'skwebtrial.appspot.com',
    iosBundleId: 'com.example.firebaseConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDvEZCOenjdEPIN6xKOsCQTqAZRtv-pQA',
    appId: '1:860542776358:web:b4266a2cd5e334422b22e7',
    messagingSenderId: '860542776358',
    projectId: 'skwebtrial',
    authDomain: 'skwebtrial.firebaseapp.com',
    databaseURL: 'https://skwebtrial-default-rtdb.firebaseio.com',
    storageBucket: 'skwebtrial.appspot.com',
    measurementId: 'G-VJY2NLHY5N',
  );
}
